//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QShopManagement.MODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CTPHIEUNHAP
    {
        public string MaSoPhieu { get; set; }
        public string MaHH { get; set; }
        public int SLNhap { get; set; }
        public int DonGiaNhap { get; set; }
        public string size { get; set; }
    
        public virtual tbl_HANGHOA tbl_HANGHOA { get; set; }
        public virtual tbl_PHIEUNHAPKHO tbl_PHIEUNHAPKHO { get; set; }
    }
}
