//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QShopManagement.MODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CTHOADON
    {
        public string MaHD { get; set; }
        public string MaHH { get; set; }
        public int Soluong { get; set; }
        public string size { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_HANGHOA tbl_HANGHOA { get; set; }
        public virtual tbl_HOADON tbl_HOADON { get; set; }
    }
}
