//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QShopManagement.MODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_NHANVIEN()
        {
            this.tbl_HOADON = new HashSet<tbl_HOADON>();
            this.tbl_TAIKHOAN = new HashSet<tbl_TAIKHOAN>();
        }
    
        public string MSNV { get; set; }
        public string TenNV { get; set; }
        public string GTNV { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NamSinh { get; set; }
        public string QueQuan { get; set; }
        public string ChucVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOADON> tbl_HOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TAIKHOAN> tbl_TAIKHOAN { get; set; }
    }
}
