//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QShopManagement.MODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HOADON()
        {
            this.tbl_CTHOADON = new HashSet<tbl_CTHOADON>();
        }
    
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public string MSNV { get; set; }
        public System.DateTime NgayXuatKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTHOADON> tbl_CTHOADON { get; set; }
        public virtual tbl_KHACHHANG tbl_KHACHHANG { get; set; }
        public virtual tbl_NHANVIEN tbl_NHANVIEN { get; set; }
    }
}
