//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QShopManagement.MODEL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HANGHOA()
        {
            this.tbl_CTHOADON = new HashSet<tbl_CTHOADON>();
            this.tbl_CTPHIEUNHAP = new HashSet<tbl_CTPHIEUNHAP>();
        }
    
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public string Loaivai { get; set; }
        public string Size { get; set; }
        public int Gia { get; set; }
        public int Soluong { get; set; }
        public int SoluongTon { get; set; }
        public string MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTHOADON> tbl_CTHOADON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CTPHIEUNHAP> tbl_CTPHIEUNHAP { get; set; }
        public virtual tbl_NHACUNGCAP tbl_NHACUNGCAP { get; set; }
    }
}
